### ISSUE TITLE
Alienware M17 R4, 2022

### ISSUE THREAD

**Issue by tbbennett2121** [Shidell/OpenCaldera#10]
AGA configured and attached but won't power up--PSU works, but laptop right now doesn't see anything.  Running OpenCaldera.exe from an elevated Command Prompt in Windows 11 provides the following output:

Unhandled Exception: System.TypeLoadException: Could not load type 'AlienLabs.GraphicsAmplifier.Domain.GraphicsAmplifierBIOSProvider' from assembly 'GraphicsAmplifier.Domain, Version=1.6.0.0, Culture=neutral, PublicKeyToken=bebb3c8816410241'.
   at OpenCaldera.Program.ReadAGABIOSProperties()
   at OpenCaldera.Program.Main(String[] args)

**Comment by Shidell** [comment]
Is your laptop's firmware up to date? What GPU are you using in the AGA? Does it power up when you turn the laptop on? Is it recognized in the Device Manager, with or without an exclamation point? Do any other new devices show up?

**Comment by tbbennett2121** [comment]
Hi Shidell!  Thank you for the quick response.

This is an Alienware m17R4, purchased in 2021, with the following details:
Yes, firmware is up to date, just checked again this morning including a check of the VBIOS for the built-in card.
Intel Core i9 10980HK processor
32GB DDR4 2933 RAM
RTX 3070 8GB (also using latest nVidia drivers + GeForce experience)

The AGA contains an RTX 2080 TI FE
The AGA does not power up when I turn the laptop on.
I checked to be sure all cables were correctly attached both inside and out.
I made sure the outlet the AGA is plugged into is working.
I see nothing in the device manager either, not even an "unknown device"

So right now I'm hoping that I can install a driver or other app that will let the laptop "see" the AGA and power it up.

I have not used the AGA before, so I'm not sure if there's any other way it's supposed to "power up" beyond following the steps in the AGA instruction guide.

I also have an AGA Fn key (F1) on the laptop, but pressing that or pressing and holding do nothing.

Hope this is helpful to you!  I'll gladly answer any other questions.



________________________________

**Comment by tbbennett2121** [comment]
Update:


  1.  I started down this road because I couldn't get a version of the Dell AGA driver compatible with Windows 11 - all others would refuse to install with a 'not compatible' message.
  2.  I just happen to have a second AGA--I bought one for me and one for my daughter who is an animator.  I put the second AGA together, and that one would at least power on
  3.  Windows 11 then decided that a responsive AGA should warrant a perpetual BSOD loop, forever...but I did at one point get it to Windows 11, see the AGA in the device manager, and try running your .exe again, and received the same output

I just wiped Windows 11 completely and am now letting the factory Win 10 release do its update dance.  After that happens, I will try installing your app again.

Thank you!

Trenton Blake Bennett
http://www.trentonbennett.com


________________________________

**Comment by Shidell** [comment]
@tbbennett2121 OK, there's a couple of things that could be at play in you/your daughter's situation. Does she have the same make/model?

- First, if the second AGA will power on (but yields a BSOD or a Not Compatible message (?)), I'd encourage you to check the first AGA again, and make sure the PSU power cables are seated properly in the 2080Ti FE. **The stock AGA PSU is rated for 460w but can likely not provide that peak, and will sustain much less—especially given the age of the PSU in the AGAs at this point (they are multiple years old). If you have an older GPU with a smaller power draw you can use to test, I recommend doing so.** It sounds to me that the PSU in the first AGA may not be up to the job of powering the 2080Ti, but that's just a guess based on what you've said so far, you'll have to do more testing, like possibly switching the PSUs between the two.
- I'd recommend sticking with Win11, but Win10 should work too. You should check out my post here: https://www.reddit.com/r/Alienware/comments/nk718z/the_state_of_the_alienware_graphics_amplifier_in/ and follow the HackFlags section to ensure that Windows can interface with the GPU correctly and not run into Code 12/31 errors.
- Do you or your daughter's laptop have the 300Hz screen? Models with the 300Hz screen do not have Optimus support, and can lead to some trouble in getting the AGA to work.
- You should also check your firmware (BIOS) to see if you have a MUX switch (option to enable/disable the built-in dGPU, in your case, the 3070M), as sometimes disabling this and leaving only the Intel iGPU (built-in with your CPU) can fix compatibility issues.

Please note that if you intend to use a 2080Ti FE (or other high-draw cards, like an RTX 3080 or newer, or RX 6800 XT or better), you should consider replacing the PSU in the AGA with a newer, more powerful unit. Certainly, test that you can get things working, especially if one AGA seems to be supporting POST and boot (..at least until BSOD, which might be rectified with the HackFlags settings above), but if you intend to use high-draw cards under a sustained workload (gaming, productivity), the stock PSU is most likely not up to the task.

**Comment by tbbennett2121** [comment]
I can't thank you enough for this advice. I'll have more to say later when I can try this but it's on hold for now due to a coming storm. I should be responding again later this weekLooking forward to seeing if I can get this working! On Sep 27, 2022 12:32 AM, Shidell ***@***.***> wrote:

@tbbennett2121 OK, there's a couple of things that could be at play in you/your daughter's situation. Does she have the same make/model?

First, if the second AGA will power on (but yields a BSOD or a Not Compatible message (?)), I'd encourage you to check the first AGA again, and make sure the PSU power cables are seated properly in the 2080Ti FE. The stock AGA PSU is rated for 460w but can likely not provide that peak, and will sustain much less—especially given the age of the PSU in the AGAs at this point (they are multiple years old). If you have an older GPU with a smaller power draw you can use to test, I recommend doing so. It sounds to me that the PSU in the first AGA may not be up to the job of powering the 2080Ti, but that's just a guess based on what you've said so far, you'll have to do more testing, like possibly switching the PSUs between the two.I'd recommend sticking with Win11, but Win10 should work too. You should check out my post here: https://www.reddit.com/r/Alienware/comments/nk718z/the_state_of_the_alienware_graphics_amplifier_in/ and follow the HackFlags section to ensure that Windows can interface with the GPU correctly and not run into Code 12/31 errors.Do you or your daughter's laptop have the 300Hz screen? Models with the 300Hz screen do not have Optimus support, and can lead to some trouble in getting the AGA to work.You should also check your firmware (BIOS) to see if you have a MUX switch (option to enable/disable the built-in dGPU, in your case, the 3070M), as sometimes disabling this and leaving only the Intel iGPU (built-in with your CPU) can fix compatibility issues.

**Comment by tbbennett2121** [comment]
Hi Shidell:
It's taken me longer than I expected, but I wanted you to know that I did spend time carefully testing OpenCaldera on more than one machine.  I now need to organize the results in an easy-to-post way and I'll reply back here as soon as I have that information.  Long story short, I loved the Reddit thread, that was huge, and I have three machines in my home that I slowly walked through and received fairly similar results.  Since this is an error thread I will provide you proper details and the one question that I'll need to ask you.
Thanks for your patience and your hard work!

-T

**Comment by tbbennett2121** [comment]
Sorry for the delay - we lost time (but nothing else) due to Hurricane Ian and then I had to go out of town.  So now I have some information for you and I'll give you an overview.  All machines are running Windows 10 Pro 64-bit and all firmware/drivers are up to date.

Look over what you find useful, ignore the rest, and let me know if you have questions or would like me to try anything different.

AGA #1 seems to work fine with the 2080 TI, AGA #2 definitely had a DOA PSU; I've ordered two Corsair PSUs as you recommended and I'll upgrade both AGAs once this is all sorted.

This is an Area-51m, an M17R3 and an M17R4.  Detailed specs (including screen types) and the steps I took are in this Excel spreadsheet:
[AGA-Tests.xlsx](https://github.com/Shidell/OpenCaldera/files/9760519/AGA-Tests.xlsx)

Screenshot of the BIOS - none appear to have any settings related to Optimus despite one prompting to reboot to enable Optimus:
![BIOS_Area-51m](https://user-images.githubusercontent.com/114438085/195223272-0e941483-a3d7-464e-84fd-c5efd9bc6f99.jpg)
![BIOS_M17R4](https://user-images.githubusercontent.com/114438085/195223295-b99a07ba-a0a9-498f-9d0b-d9a811bce7f2.jpg)

First tried installing Dell's AGA drivers, and all returned the same message:
![Dell-AGA-Driver-Install-Message](https://user-images.githubusercontent.com/114438085/195223372-b720806b-7b88-4917-b0c7-813c4adc459b.jpg)

DxDiags:
[DxDiag_AW17R3.txt](https://github.com/Shidell/OpenCaldera/files/9760521/DxDiag_AW17R3.txt)
[DxDiag_AW17R4.txt](https://github.com/Shidell/OpenCaldera/files/9760522/DxDiag_AW17R4.txt)
[DxDiag_AW51M.txt](https://github.com/Shidell/OpenCaldera/files/9760524/DxDiag_AW51M.txt)

nVidia Control Panel UI change (see Excel sheet):
![nVidia-Control-Panel_GPU-Select](https://user-images.githubusercontent.com/114438085/195223448-2c991966-31a5-4c7e-bb45-7dceef275f96.jpg)

nVidia System Info exports:
[nVidia-Info_AW51M-NVIDIA System Information 10-01-2022 18-32-28.txt](https://github.com/Shidell/OpenCaldera/files/9760535/nVidia-Info_AW51M-NVIDIA.System.Information.10-01-2022.18-32-28.txt)
[nVidia-Info_AW17R3-NVIDIA System Information 10-01-2022 17-32-28.txt](https://github.com/Shidell/OpenCaldera/files/9760532/nVidia-Info_AW17R3-NVIDIA.System.Information.10-01-2022.17-32-28.txt)
[nVidia-Info_AW17R4-NVIDIA System Information 10-01-2022 20-36-28.txt](https://github.com/Shidell/OpenCaldera/files/9760533/nVidia-Info_AW17R4-NVIDIA.System.Information.10-01-2022.20-36-28.txt)

Results of trying to run OpenCaldera on each machine:

[Results-AW17R3.txt](https://github.com/Shidell/OpenCaldera/files/9760565/Results-AW17R3.txt)
[Results-AW17R3-Optimus-ON.txt](https://github.com/Shidell/OpenCaldera/files/9760566/Results-AW17R3-Optimus-ON.txt)
[Results-AW17R4.txt](https://github.com/Shidell/OpenCaldera/files/9760567/Results-AW17R4.txt)
[Results-AW51M.txt](https://github.com/Shidell/OpenCaldera/files/9760568/Results-AW51M.txt)

Summary notes:
[Overall-Notes.txt](https://github.com/Shidell/OpenCaldera/files/9760536/Overall-Notes.txt)


Current conclusion is that support for both GPUs appears to be more out-of-the-box and not need anything...but also doesn't appear to offer a mechanism to choose one or the other, but instead balances the load and favors the AGA by giving it more to do.

I'm not in any hurry to hear back and I am willing to test any other scenarios.  I need to talk my wife and daughter into letting me install Furmark or 3DMark or some such on their machines to test in more detail.

EDIT: fix broken link

**Comment by Shidell** [comment]
@tbbennett2121 Sorry to hear you were affected by Ian, but glad you're OK and didn't suffer anything more than loss of time.

I looked over your information and believe everything is looking good; the AGA is working as expected, with the external GPU being detected and installed in each system, and (seemingly?) used. You don't need to install any drivers for the AGA, so don't worry about that package failing.

**When using/testing with the AGA, are you connecting an external monitor to the eGPU, or are you continuing to use the laptop display?** Routing data to the eGPU is fairly efficient, given the bandwidth, but if you route the display data back, you'll both take a hit on performance, _and_ engage the dGPU or iGPU, as it's what's actually connected to the laptop display itself. For example, if you render on your 2080Ti in the AGA, but use the laptop display, the rendered frame(s) come back over the AGA cable (which eats into performance), and then get copied to the dGPU/iGPU framebuffer before being presented to the laptop. It's doable, but you should expect performance loss, and you might have some... interesting behavior, like both GPUs appearing to be active, like you mentioned. The suggested use is with an external monitor, but it isn't absolutely necessary.

In Windows 11, you can select the "Default Graphics Settings", in this panel: 

![image](https://user-images.githubusercontent.com/13051323/195241728-c63497d2-2deb-4704-b777-b566a17a4ea8.png)

In Windows 10, you'd want to look for similar—or update to Windows 11, if possible—and dictate to Windows which GPU should be used (this is what Nvidia's Control Panel is referring to.)

I do know that 3DMark allows you to pick the GPU to test before testing, and so you could explicitly choose amongst the available GPUs and bench each, and you should most certainly see a big difference in performance.

**Comment by tbbennett2121** [comment]
Whoops - I thought I had also shared the Windows Control Panel screen that I'm seeing in Win 10 Pro:

![Windows-Control-Panel_GPU-Options-1](https://user-images.githubusercontent.com/114438085/195466043-523c5f75-7619-41e7-964c-1cc6bc1cd8e0.jpg)

![Windows-Control-Panel_GPU-Options-2](https://user-images.githubusercontent.com/114438085/195466070-06a0d787-e02d-42ce-a695-edbe6d7e4ed5.jpg)

This helps a lot with my understanding of how the AGA should function (and my apologies if I seem clueless--I find that the Dell manual isn't very helpful beyond how to put the card in and close the lid).

Right now I have a corner of my home office set up as a makeshift test bench, so I was using the laptop display.  Now I understand what the dGPU/iGPU were doing.  When my daughter moves I'll be getting her a good animation display (high frame rate, color correct, etc.) and she'll take one of these AGAs with her.  The other I'll use on my older (2018) Alienware 120Hz UHD 3440x1440 display.

Two quick questions:
1) Should I try running a benchmark or game using only an external monitor?
2) When I can't select the GPU as you show in this Win 11 screen here, would "Show only on 2" in Display settings accomplish the same thing because it turns off the laptop display?

(I realize you may not know the answer to that second one).

Then the easier question:  does this mean OpenCaldera has no real relevance for me?

**Comment by Shidell** [comment]
1. Yeah; you could try, for example, running 3DMark on the laptop display and external display, and comparing results. Again, you can select the GPU to be used, so it's a good testing tool.
2. Win11's ability to select/prioritize the GPU to be used is really nice; it might be a selling point in and of itself for users like ourselves, with eGPU setups—if Windows 10 doesn't provide any similar mechanism, then you may be at the mercy of the GPU that Windows selects for any given task, if you can't select it yourself (e.g. 3DMark.) Yes, theoretically, disabling the laptop display and only displaying on the external monitor should then cause everything to be routed to the eGPU, so it's effectively forcing the system to use the eGPU. (Again, if you test with the laptop and external display, selecting the different GPUs via 3DMark, you should notice a performance hit from the eGPU if coming back to the laptop display, as opposed to going to the external display.)

OpenCaldera is kind of irrelevant; I created it as a tool to try to discover what was preventing RTX 3000 series GPUs from working with the AGA. I discovered there was no reason, it was purely a software issue (an issue with Nvidia's driver installer) that was preventing the drivers for 3000 series from being installed properly. Once Nvidia fixed that issue, there is no compatibility issue (aside from potentially needing to use HackFlags so Windows can address the extra resources), so it isn't real useful any longer, and I didn't bother maintaining or updating it, because everything is working now as expected.

I keep the project (this) up, though, just like the reddit thread, to help others who have problems or questions regarding the AGA and newer GPUs. :)
