### ISSUE TITLE
Error running 0.1.1.0

### ISSUE THREAD

**Issue by cyberant-security** [Shidell/OpenCaldera#5]
My system:
Windows 10 64 Bit 20H2
Alienware M15 R2 with AGA running with RTX 2060 Ti (with Error Code 31 in Device Manager)
Dot Net 4.8 is installed 

Running Opencaldera 0.1.1.0 from the release download  I get an error. also tried compiling from source and errors also.

OpenCaldera 0.1.1.0

Unhandled Exception: System.TypeLoadException: Could not load type 'AlienLabs.GraphicsAmplifier.Domain.GraphicsAmplifierBIOSProvider' from assembly 'GraphicsAmplifier.Domain, Version=1.6.0.0, Culture=neutral, PublicKeyToken=bebb3c8816410241'.
   at OpenCaldera.Program.ReadAGABIOSProperties()
   at OpenCaldera.Program.Main(String[] args)

Any ideas?

**Comment by Shidell** [comment]
Do you have the Alienware Control Center or Alienware Graphics Amplifier software installed?

**Comment by wildonrio** [comment]
I am not the OP, but am getting the exact same error message in OpenCaldera. My system is quite different however. I have an m15 R4 running an EVGA 3090 FTW3 Ultra installed in my AGA. I also got the same error message when running a Gigabyte RX 6900 XT, so it does not appear to be related to the type of card installed.

In Device Manager, my 3090 shows Error Code 31, but my 6900 XT doesn't show up in Device Manager at all.

EDIT: I do not have the Alienware Graphics Amplifier software installed since it's incompatible with my system, but I do have Alienware Command Center installed.

**Comment by Zero1234567888** [comment]
Hello, not OP but I have the same issue. I am looking for some advice. Area 51m r2, with Alienware command center.
